# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'birra',
                'verbose_name_plural': 'birres',
            },
        ),
        migrations.CreateModel(
            name='Edicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicio', models.IntegerField(unique=True)),
                ('totalBirres', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'edicio',
                'verbose_name_plural': 'edicions',
            },
        ),
        migrations.CreateModel(
            name='Tirador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('totalBirresTirador', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', null=True, protocol='IPv4')),
                ('edicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ComptaBirres.Edicio')),
            ],
            options={
                'verbose_name': 'tirador',
                'verbose_name_plural': 'tiradors',
            },
        ),
        migrations.AddField(
            model_name='birra',
            name='edicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComptaBirres.Edicio'),
        ),
        migrations.AddField(
            model_name='birra',
            name='tirador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComptaBirres.Tirador'),
        ),
    ]
