# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComptaBirres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birra',
            name='edicio',
        ),
    ]
