# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptaBirres', '0002_remove_birra_edicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicio',
            name='dataString',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
