# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptaBirres', '0003_edicio_datastring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicio',
            name='dataString',
            field=models.TextField(null=True),
        ),
    ]
