# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComptaBirres', '0004_auto_20190507_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicio',
            name='dataString',
            field=models.TextField(default='[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]', editable=False),
        ),
    ]
